define({
"Size":"长度必须介于{min}和{max}之间",
"Size.Exact":"长度必须为{max}",
"DecimalMax":"长度须不大于{value}",
"DecimalMin":"长度须不小于{value}",
"NotNull":"不能为空",
"Digits":"必须是数字",
"NotValidType":"不是有效的{typeName}",
"form.reset.prompt":"是否确认放弃更改？",
"form.sumbit-failed.prompt":"提交表单【{formDesc}】数据失败：\n{error}"
});
