define({
	 "sampleCustomRule":"cannot have {key}",
	 "info.viscenthuang.demo.bo.Numeric":"must be numeric of less {max}",
     "form.submit.ok":"Data submitted.\nMember ID:{memberId}",
     "firstname":"First name:",
     "lastname":"Last name:",
     "passwd":"Password:",
     "passwd.retype":"Password(re-type):",
     "gender":"Gender:",
     "gender.male":"Male",
     "gender.female":"Female",
     "birthdate":"Date of birth:",
     "pref-lang":"Prefered Language:",
     "expertise-area":"Expertise areas:",
     "email":"Email:",
     "mobilephone":"Mobilephone:",
     "notify-channel":"Notification channel:",
     "notify-channel.email":"By email",
     "notify-channel.sms":"By SMS",
     "intro":"Introduction:",
     "mgmt-expierence":"Management expierence:",
     "hour":"hour(s)",
     "update":"Update",
     "Reset":"Discard Change(s)",
     "change.lang":"Change Language(Require page reload):",
     "change.lang.tip":"This will reload current page,are you sure?",
      "demo.explain.toggle":"Show Demo Explanation",
     "demo.explain":"demo explain...",
     "pwd.not.match":"Passowrd and password-retype do not match",
     "form.title":"Member Registration Information",
     "passwd.tip":"(The password itself will not be submitted,only hash of password will be submitted!)",
     "demo.showlog":"Show Log"
});